// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebAppMVCFootball.Models;

public partial class FootballContext : DbContext
{
    public FootballContext()
    {
    }

    public FootballContext(DbContextOptions<FootballContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TCampionato> TCampionatos { get; set; }

    public virtual DbSet<TGiocatore> TGiocatores { get; set; }

    public virtual DbSet<TSquadra> TSquadras { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=EDI-PC;Initial Catalog=Football;User ID=Football;Password=root; Integrated Security = False; TrustServerCertificate=Yes");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TGiocatore>(entity =>
        {
            entity.HasOne(d => d.IdSquadraNavigation).WithMany(p => p.TGiocatores).HasConstraintName("FK_T_Giocatore_T_Squadra");
        });

        modelBuilder.Entity<TSquadra>(entity =>
        {
            entity.HasOne(d => d.IdCampionatoNavigation).WithMany(p => p.TSquadras).HasConstraintName("FK_T_Squadra_T_Campionato");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}