// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppMVCFootball.Models;

[Table("T_Campionato")]
public partial class TCampionato
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(50)]
    public string Nome { get; set; }

    [StringLength(50)]
    public string Paese { get; set; }

    [StringLength(50)]
    public string NomeFederazione { get; set; }

    [Column("isTopRanking")]
    public bool? IsTopRanking { get; set; }

    [InverseProperty("IdCampionatoNavigation")]
    public virtual ICollection<TSquadra> TSquadras { get; set; } = new List<TSquadra>();
}