// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppMVCFootball.Models;

[Table("T_Giocatore")]
public partial class TGiocatore
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(50)]
    public string Nome { get; set; }

    public int? Eta { get; set; }

    public int? IdSquadra { get; set; }

    [StringLength(50)]
    public string Nazionalita { get; set; }

    [ForeignKey("IdSquadra")]
    [InverseProperty("TGiocatores")]
    public virtual TSquadra IdSquadraNavigation { get; set; }
}