// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppMVCFootball.Models;

[Table("T_Squadra")]
public partial class TSquadra
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int? IdCampionato { get; set; }

    [StringLength(50)]
    public string Nome { get; set; }

    public int? AnnoFondazione { get; set; }

    [ForeignKey("IdCampionato")]
    [InverseProperty("TSquadras")]
    public virtual TCampionato IdCampionatoNavigation { get; set; }

    [InverseProperty("IdSquadraNavigation")]
    public virtual ICollection<TGiocatore> TGiocatores { get; set; } = new List<TGiocatore>();
}